<template>
  <div class='raspberrypi'>
    <v-container fluid class='RogueComponent RoguePager'>
      <v-slide-y-transition mode='out-in'>
        <v-layout column align-center>
          <v-avatar class='hidden-sm-and-down RogueImage' size='172px' >
            <img src='../assets/img/Logo-192x192.svg' alt='Rogue Designs'>
          </v-avatar>
          <v-avatar class='hidden-md-and-up RogueImage' size='84px' >
            <img src='../assets/img/Logo-192x192.svg' alt='Rogue Designs'>
          </v-avatar>
            <p class='headline'>Rogue Designs</p>
            <p class='title'>RaspberryPi Services</p>        
        </v-layout>
      </v-slide-y-transition>
      <v-layout column class='RogueLayout'>
        <v-flex xs12 sm12 md8 lg6 xl6>          
          <v-toolbar color='primary'>
            <v-toolbar-title class='black--text RogueToolbarTitle title'>RaspberryPi Images</v-toolbar-title>
            <v-spacer></v-spacer>
          </v-toolbar>
          <v-card>
            <v-card-title class='title'>Media Search/Downloader</v-card-title>
              <ul class='subheading RogueUL' style='list-style-type:disc'>
                <li><p>Integrated TV-Shows/Movies/Music Downloader</p></li>
                <li><p>Automatically search and download your favorite media. Automatically searches for your favorite TV-Shows. Automatically downloads them as soon as they become available.</p></li>
                <li><p>Intgrates with web browser to easily manage your media.</p></li>
                <li><p>Uses OpenVPN to keep your connections secure.</p></li>
              </ul>
              <v-img>
                <img src='../assets/img/HTPCManager.png' alt='HTPC Manager'>
              </v-img>
            <v-card-actions class='RogueCardActions'>
              <v-btn round dark small color='primary' @click='$router.push("/contact")'>Contact</v-btn>
            </v-card-actions>
            <v-divider></v-divider>
            <v-card-title class='title'>VPN</v-card-title>
              <ul class='subheading RogueUL' style='list-style-type:disc'>
                <li><p>Uses OpenVPN to establish a secure connection to any site you wish to go to. Tunnels trough with https so less of a chance of ISP discovering you are using a VPN.</p></li>
                <li><p>No month cost, OpenVPN certificates are generated by the RaspberryPi.</p></li>
                <li><p>With the FCC deregulating the ISP's, the only way to insure the same connection to your favorite websites is with a VPN (Virtual Private Network). VPN's protect you from being observed from your ISP or any hackers on the internet.</p></li>
              </ul>
            <v-card-actions class='RogueCardActions'>
              <v-btn round dark small color='primary' @click='$router.push("/contact")'>Contact</v-btn>
            </v-card-actions>
            <v-divider></v-divider>
            <v-card-title class='title'>Media Server</v-card-title>
              <ul class='subheading RogueUL' style='list-style-type:disc'>
                <li><p>Can be installed with Plex Media Server or Open Media Server. Automatically, catalog and watch all your media. Can be connected to any external USB Drive.</p></li>
                <li><p>Plex and Open Media Server can use DLNA to stream your media.</p></li>
              </ul>
            <v-card-actions class='RogueCardActions'>
              <v-btn dark round small color='primary' @click='$router.push("/contact")'>Contact</v-btn>
            </v-card-actions>
            <v-divider></v-divider>            
            <v-card-title class='title'>Proxy Server</v-card-title>
              <ul class='subheading RogueUL' style='list-style-type:disc'>
                <li><p>Setup a proxy server to block ads, track internet usage. Setup Blacklists to prevent children from seeing adult content.</p></li>
              </ul>
            <v-card-actions class='RogueCardActions'>
              <v-btn dark round small color='primary' @click='$router.push("/contact")'>Contact</v-btn>
            </v-card-actions>
            <v-divider></v-divider>
          </v-card>
        </v-flex>
      </v-layout>
    </v-container>
  </div>
</template>

<script>
  export default {
    name: 'raspberrypi'  
  }
</script>
